### ISSUE TITLE
Unable to compile code. External Custom file missing

### ISSUE THREAD

**Issue by 0xad1onchain** [code-423n4/2021-09-wildcredit#1]
`File ./SafeMath.sol, not found`

This codebase seems to use a SafeMath which supports printing custom error messages while performing operations. 
Kindly add the Library to the codebase. 

@talegift

**Comment by talegift** [comment]
There are a lot of other files this project uses. They are not included in this repo since we were asked to reduce the scope (number of files and LOC) so they are not a part of the review.

**Comment by 0xad1onchain** [comment]
That is a very custom file. Kindly provide an external link to the file or add the file to the codebase. The codebase cannot be compiled without it

**Comment by BarBozz** [comment]
Plz check if this could be used: https://github.com/WildCredit/contracts/tree/master/contracts/external

**this i a foreign repo, not under audit, just for reference**

**Comment by BarBozz** [comment]
@talegift  most certain we could remove the import at https://github.com/code-423n4/2021-09-wildcredit/blob/main/contracts/external/SafeERC20.sol#L6 without any impact. Right?
